; $Header$
;
; Millennium Operating System
; Copyright 1997-1998 (c) Leprechaun Software.  All Rights Reserved.
;

GLOBAL	Except_Div:PROC
GLOBAL	Except_Debug:PROC
GLOBAL	Except_NMI:PROC
GLOBAL	Except_BreakPt:PROC
GLOBAL	Except_OverFlow:PROC
GLOBAL	Except_RangeExc:PROC
GLOBAL	Except_InvOpCode:PROC
GLOBAL	Except_DeviceNA:PROC
GLOBAL	Except_Double:PROC
GLOBAL	Except_CoProcess:PROC
GLOBAL	Except_TSS:PROC
GLOBAL	Except_Segment:PROC
GLOBAL	Except_Stack:PROC
GLOBAL	Except_GP:PROC
GLOBAL	Except_Page:PROC
GLOBAL	Except_FloatingPt:PROC
GLOBAL	Except_Reserved:PROC
GLOBAL	Except_AlignChk:PROC
GLOBAL	Except_MachineChk:PROC
