STDLIB = abort.o abs.o atexit.o atof.o atoi.o atol.o atold.o bsearch.o \
	 div.o ldiv.o exec.o malloc.o rand.o system.o exit.o \
	 labs.o qsort.o strtol.o strtoul.o errno.o strtod.o strtold.o
OBJS += $(addprefix stdlib/, $(STDLIB))

