STRING = memchr.o memcmp.o memcpy.o memset.o strcat.o strchr.o strcmp.o \
	 strcpy.o strlen.o strlwr.o strupr.o strncat.o strncpy.o strncmp.o \
	 strrchr.o strcspn.o strcoll.o strpbrk.o \
	 strspn.o strstr.o strtok.o strxfrm.o
OBJS += $(addprefix string/, $(STRING))

